### PR TITLE
Added Windows Discover Services

### PR DESCRIPTION
**Pull request by rohitsangwan01**

### CODE REVIEW

**Comment by rohitsangwan01** [comment]
@Sunbreak if this one seems fine , maybe we can add this to main quick_ble too , i know its not necessary to discover services in windows  , but just to complete features checklist

**Comment by Sunbreak** [comment]
Sure. Looks better than 'UnimplementError'

**Comment by Sunbreak** [comment]
Updated format. Could you take a look or try?

**Comment by rohitsangwan01** [comment]
@Sunbreak for me  `msg["characteristics"] = characteristics;` was not working
so replaced that with `msg.insert({"characteristics", characteristics});` , working fine now

**Comment by Sunbreak** [comment]
> @Sunbreak for me `msg["characteristics"] = characteristics;` was not working so replaced that with `msg.insert({"characteristics", characteristics});` , working fine now

https://www.dynamsoft.com/codepool/writing-cpp-flutter-barcode-plugin-windows.html

It could be `map[EncodableValue("format")] = results->results[index]->barcodeFormatString;`

**Pull request merged**
