### PR TITLE
[quick_blue] Check illegal characteristic identifier on Windows

### PR DESCRIPTION
**Pull request by Sunbreak**
Follow up to #27

### CODE REVIEW

**Comment by Sunbreak** [comment]
@rohitsangwan01 Could you take a look at?

**Comment by Sunbreak** [comment]
A more elegant solution for https://github.com/woodemi/quick_blue/pull/107

@kinyoklion, Could you take a look?

**Comment by kinyoklion** [comment]
> A more elegant solution for [woodemi/quick_blue#107](https://github.com/woodemi/quick_blue/pull/107)
> 
> @kinyoklion, Could you take a look?

An illegal/missing characteristic isn't what #107 attempts to address. What #107 addresses is that there are race conditions between accessing a valid device/characteristic and the completion of those operations. Starting a read/write operation with a perfectly valid device and characteristic can still fail, and still throw an exception. This applies to every invocation of a winrt method that involves a device (Not creating a descriptor for instance).

This does improve the situation for some specific cases, because there are fewer cases where it can fail. But flatly, unless the exceptions are handled, or potentially the winrt generation is altered to not throw and instead operate on hresults, it will never be stable.

This function itself is problematic because GetCharacteristicsAsync() can throw.
```
 IAsyncOperation<GattCharacteristic> GetCharacteristicAsync(std::string service, std::string characteristic) {
    if (gattCharacteristics.count(characteristic) == 0) {
      auto gattService = co_await GetServiceAsync(service);
      auto characteristicResult = co_await gattService.GetCharacteristicsAsync();
      if (characteristicResult.Status() != GattCommunicationStatus::Success)
        co_return nullptr;
      for (auto c : characteristicResult.Characteristics())
        if (to_uuidstr(c.Uuid()) == characteristic)
          gattCharacteristics.insert(std::make_pair(characteristic, c));
    }
    co_return gattCharacteristics.at(characteristic);
  }
};
```

For instance line 521 `auto readValueResult = co_await gattCharacteristic.ReadValueAsync();`. This can still throw an exception even if you have a valid characteristic to start with. Because between getting that characteristic, and reading it, the state can change. (The device turns off, you place yourself between the radio and the device, etc.)

**Comment by Sunbreak** [comment]
Yep. Going to handle the exception in other PRs.

What do you think about this PR, especially how this PR uses `std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>> result`

```cpp
    auto async_c = bluetoothAgent.GetCharacteristicAsync(service, characteristic);
    async_c.Completed([&, result_pointer = result.get()]
        (IAsyncOperation<GattCharacteristic> const& sender, AsyncStatus const args){
          auto c = sender.GetResults();
          if (c == nullptr) {
            result->Error("IllegalArgument", "Unknown characteristic:" + characteristic);
            return;
          }
          WriteValueAsync(c, value, bleOutputProperty);
          result->Success(nullptr);
        });
```

> I'm not sure about C++ coroutines, especially experimental coroutine support of C++/WinRT patched onto C++ 17: https://github.com/woodemi/quick_blue/issues/110#issuecomment-1146985554

I think it is safer and clearer to use `result` in lambda for a quick search of `characteristic`, than pass it to `asychronous function`s as you mentioned: https://github.com/woodemi/quick_blue/issues/110#issuecomment-1146686957

**Comment by kinyoklion** [comment]
> Yep. Going to handle the exception in other PRs.
> 
> What do you think about this PR, especially how this PR uses `std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>> result`
> 
> ```c++
>     auto async_c = bluetoothAgent.GetCharacteristicAsync(service, characteristic);
>     async_c.Completed([&, result_pointer = result.get()]
>         (IAsyncOperation<GattCharacteristic> const& sender, AsyncStatus const args){
>           auto c = sender.GetResults();
>           if (c == nullptr) {
>             result->Error("IllegalArgument", "Unknown characteristic:" + characteristic);
>             return;
>           }
>           WriteValueAsync(c, value, bleOutputProperty);
>           result->Success(nullptr);
>         });
> ```
> 
> > I'm not sure about C++ coroutines, especially experimental coroutine support of C++/WinRT patched onto C++ 17: [woodemi/quick_blue#110 (comment)](https://github.com/woodemi/quick_blue/issues/110#issuecomment-1146985554)
> 
> I think it is safer and clearer to use `result` in lambda for a quick search of `characteristic`, than pass it to `asychronous function`s as you mentioned: [woodemi/quick_blue#110 (comment)](https://github.com/woodemi/quick_blue/issues/110#issuecomment-1146686957)

I think the change is probably fine, but I do not think it will be any better/safer than a co-routine. A callback could equally easily be on a different thread. If the callback is on the same thread, then almost certainly resuming a coroutine would also be. I was going to run some testing with awaiting. Personally I prefer await in code when available, because it is more composable.

**Comment by kinyoklion** [comment]
> Yep. Going to handle the exception in other PRs.
> 
> What do you think about this PR, especially how this PR uses `std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>> result`
> 
> ```c++
>     auto async_c = bluetoothAgent.GetCharacteristicAsync(service, characteristic);
>     async_c.Completed([&, result_pointer = result.get()]
>         (IAsyncOperation<GattCharacteristic> const& sender, AsyncStatus const args){
>           auto c = sender.GetResults();
>           if (c == nullptr) {
>             result->Error("IllegalArgument", "Unknown characteristic:" + characteristic);
>             return;
>           }
>           WriteValueAsync(c, value, bleOutputProperty);
>           result->Success(nullptr);
>         });
> ```
> 
> > I'm not sure about C++ coroutines, especially experimental coroutine support of C++/WinRT patched onto C++ 17: [woodemi/quick_blue#110 (comment)](https://github.com/woodemi/quick_blue/issues/110#issuecomment-1146985554)
> 
> I think it is safer and clearer to use `result` in lambda for a quick search of `characteristic`, than pass it to `asychronous function`s as you mentioned: [woodemi/quick_blue#110 (comment)](https://github.com/woodemi/quick_blue/issues/110#issuecomment-1146686957)

I do not think it is any more or less safe, just more verbose.

The behavior of the `co_await` is to resume on the same UI thread if called from a UI thread, or to resume on a background thread. The background thread may not be the same.

If the code is currently resuming on multiple threads, then basically already none of it is correct. There are not any synchronization primitives being used, so it could be wrong.

A delegate still has to execute code someplace, and has to resume something. I've used delegates that are on other threads. 

If they were on other threads, then some signal would need to be used to wake the main thread, or you could have to use a method to invoke it on the run loop.

I did instrument the `co_await` code, and it was resuming on the same thread, but it could just happen to use the same thread, assuming it is operating on a background thread.

```
HandleMethodCall setNotifiable
The threadID we get the flutter call on 31888
The threadID we resume on31888
```

So, the right thing to do would be validate it is a UI thread, and if it is, then just use `co_await` because it is very simple and clean.

If it is not, then the code needs re-worked quite a bit.

**Comment by Sunbreak** [comment]
Thanks a lot for your info. I'll leave some `FIXME` in code at the time and fix them later

**Pull request merged**
