### PR TITLE
Add "requestPermission" option to "getDevicesWithDescription".

### PR DESCRIPTION
**Pull request by Sunbreak**
Copy of: https://github.com/woodemi/quick_usb/pull/65#event-6765828998

Signed-off-by: wangkun <wangkun@woodemi.com>

### CODE REVIEW

**Comment by Sunbreak** [comment]
@anik786 Could you take a look at this PR?

**Comment by anik786** [comment]
Seems okay.

**Comment by Sunbreak** [comment]
We'd like to conitue further development here

**Comment by anik786** [comment]
What was wrong with the original repo:
https://github.com/woodemi/quick_usb

Also isn't that the one connected to:
https://pub.dev/packages/quick_usb

**Comment by Sunbreak** [comment]
https://melos.invertase.dev/ helps to maintain mono repo

**Comment by Sunbreak** [comment]
> Also isn't that the one connected to:
> https://pub.dev/packages/quick_usb

https://pub.dev/packages/quick_usb/versions/0.4.0-dev.0 is a pre-release version from this repo

I'll archive https://github.com/woodemi/quick_usb as soon as this repo mature

**Pull request merged**
